SIP-781. Implement Sameday Cities nomenclature for Ro, Hu, BG. + Code Refactor in order to meet PSR2 coding style standard. + Update README.md

diff --git a/.github/workflows/phpcs.yml b/.github/workflows/phpcs.yml
--- a/.github/workflows/phpcs.yml
+++ b/.github/workflows/phpcs.yml
@@ -29,25 +29,18 @@ jobs:
       - name: Run PHPCS
         run: vendor/bin/phpcs --standard=phpcs.xml.dist --report=checkstyle | tee phpcs-report.xml
 
-      - name: Annotate PR with PHPCS
-        uses: reviewdog/action@v0.14.0
-        with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          reporter: github-pr-review
-          level: error
-          fail_on_error: true
-          tool_name: phpcs
-          tool_command: vendor/bin/phpcs --standard=phpcs.xml.dist
-
-      - name: PHPCS Summary (Checks tab)
-        uses: reviewdog/action@v0.14.0
-        with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          reporter: github-pr-check
-          level: error
-          fail_on_error: true
-          tool_name: phpcs
-          tool_command: vendor/bin/phpcs --standard=phpcs.xml.dist
+      - name: Run PHPCS
+        id: phpcs
+        run: |
+          echo "Rulăm PHPCS conform phpcs.xml.dist..."
+          vendor/bin/phpcs --standard=phpcs.xml.dist --report=checkstyle > phpcs-checkstyle.xml || true
+          vendor/bin/phpcs --standard=phpcs.xml.dist
+          # If there are some errors, return non 0 code
+          PHPCS_EXIT_CODE=$(vendor/bin/phpcs --standard=phpcs.xml.dist --report=summary | tail -n1 | awk '{print $2}')
+          if [ "$PHPCS_EXIT_CODE" -ne 0 ]; then
+            echo "::error file=phpcs.xml.dist::PHPCS found some issues. Check the HTML Report for more info!"
+            exit 1
+          fi
 
       - name: Generate PHPCS HTML Report
         run: vendor/bin/phpcs --standard=phpcs.xml.dist --report=full --report-file=phpcs-report.html
