SIP-781. Implement Sameday Cities nomenclature for Ro, Hu, BG. + Code Refactor in order to meet PSR2 coding style standard. + Update README.md

diff --git a/.github/workflows/phpcs.yml b/.github/workflows/phpcs.yml
--- a/.github/workflows/phpcs.yml
+++ b/.github/workflows/phpcs.yml
@@ -8,7 +8,6 @@ on:
 jobs:
   phpcs:
     runs-on: ubuntu-latest
-
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
@@ -16,7 +15,7 @@ jobs:
       - name: Setup PHP
         uses: shivammathur/setup-php@v2
         with:
-          php-version: '7.0'
+          php-version: '7.4'
 
       - name: Install PHPCS
         run: |
@@ -25,27 +24,38 @@ jobs:
           chmod +x phpcs.phar
           mv phpcs.phar vendor/bin/phpcs
 
-      - name: Run PHPCS for exit code
-        id: phpcs-exit
+      - name: Run PHPCS
+        id: phpcs
         run: |
-          vendor/bin/phpcs --standard=phpcs.xml.dist
+          vendor/bin/phpcs --standard=phpcs.xml.dist || true
           echo "PHPCS_EXIT_CODE=$?" >> $GITHUB_ENV
 
       - name: Generate PHPCS HTML Report
         run: |
           vendor/bin/phpcs --standard=phpcs.xml.dist --report=full --report-file=phpcs-report.html || true
           if [ "${{ env.PHPCS_EXIT_CODE }}" -eq 0 ]; then
-            echo "<p style='color:green; font-weight:bold;'>Good job, you are able to merge this request!</p>" >> phpcs-report.html
+            echo "<h2 style='color:green;'>Good job, you are able to merge this request!</h2>" >> phpcs-report.html
           fi
 
-      - name: Upload PHPCS HTML Artifact
-        uses: actions/upload-artifact@v4
-        with:
-          name: phpcs-html-report
-          path: phpcs-report.html
+  deploy:
+    needs: phpcs
+    runs-on: ubuntu-latest
+    permissions:
+      pages: write
+      id-token: write
+    environment:
+      name: github-pages
+      url: ${{ steps.deployment.outputs.page_url }}
+    steps:
+      - name: Deploy to GitHub Pages
+        id: deployment
+        uses: actions/deploy-pages@v4
 
-      - name: Fail if PHPCS has errors
-        if: ${{ env.PHPCS_EXIT_CODE != 0 }}
-        run: |
-          echo "::error file=phpcs.xml.dist::PHPCS a găsit erori. Verificați raportul HTML!"
+  fail-if-errors:
+    needs: phpcs
+    runs-on: ubuntu-latest
+    if: ${{ needs.phpcs.outputs.PHPCS_EXIT_CODE != 0 }}
+    steps:
+      - run: |
+          echo "::error ::PHPCS a găsit erori. Verificați raportul HTML pe GitHub Pages!"
           exit 1
